baseURL = 'https://hadooboo.github.io/'
languageCode = 'ko-kr'
title = 'Hadooboo Dev Log'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "category"
    name = "Category"
    url = "/category/"
    weight = 2

  [[menu.main]]
    identifier = "tag"
    name = "Tag"
    url = "/tag/"
    weight = 3

[taxonomies]
  category = 'category'
  tag = 'tag'
